// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rluaedkwkidkfpohgrub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdWFlZGt3a2lka2Zwb2hncnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzEwMjUsImV4cCI6MjA2MTE0NzAyNX0.Z-nS5kXx-wrCOvdWLIVS1EDWbed3rSLKk0VpG3we-i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);